### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by coaxhappy**

### CODE REVIEW

**Comment by EricZimmerman** [comment]
i am going to need more details on why you want these changes before i can merge. i get the updates to appids.txt, but why the other changes?

**Comment by coaxhappy** [comment]
> i am going to need more details on why you want these changes before i can merge. i get the updates to appids.txt, but why the other changes?

I wanna modify 'automaticDestinations-ms' file content, so I need to convert DestList entity to buffer and write the buffer to file using OpenMCDF library(https://github.com/CodeCavePro/OpenMCDF), just ignore it  if it confuse you.

**Comment by EricZimmerman** [comment]
its not a matter of confusion, but this is a library to process artifacts in a forensically sound manner, so changing contents wont be added.

of course feel free to fork the library and do what you like with it, but i do not want to add the ability to change contents for obvious reasons.

**Comment by EricZimmerman** [comment]
so for the reasons above i am going to reject these (except for the app ids, thanks!)

**Pull request closed without merging**
